{"additions": 22, "auther_ref": "P8RndmEnginePtr", "auther_sha": "e49746ce3e2eccc0d587b21eb72c0eaa8f7f1e71", "author": "mseidel42", "body": "#### PR description:\r\n\r\nPythia 8.310 expects a shared_ptr for the random number generator now, see corresponding https://github.com/cms-sw/cmsdist/pull/8938\r\n\r\nI changed `unique_ptr` with `shared_ptr` in various places and it compiles but \r\n`runTheMatrix.py -j 10 -l 14234.0`\r\ngives segfault in\r\n`#5  0x00007f6a1e22000a in gen::P8RndmEngine::setRandomEngine (v=0x7f6a20b25b80, this=0x0) at /build/mseidel/CMSSW_14_0_X_2024-01-22-2300/src/GeneratorInterface/Pythia8Interface/interface/P8RndmEngine.h:34`\r\n\r\n@wddgit I think this touches a lot of your work, could you have a look, please?\r\n\r\nUpdate: wf 14234.0 working\r\n```\r\n14234.0_TTbar_14TeV+2023FSPU Step0-PASSED Step1-PASSED Step2-PASSED  - time date Mon Jan 29 17:15:48 2024-date Mon Jan 29 17:02:10 20\r\n24; exit: 0 0 0                                                                                                                      \r\n1 1 1 tests passed, 0 0 0 failed  \r\n```", "branch": "master", "changed_files": 11, "comments": 10, "commits": 2, "created_at": "1706189590", "deletions": 18, "labels": ["fastsim-pending", "generators-pending", "pending-signatures", "tests-pending", "orp-pending", "code-checks-rejected"], "milestone": "CMSSW_14_0_X", "number": 43786, "release-notes": [], "review_comments": 6, "state": "open", "title": "Adaptions for Pythia 8.310", "updated_at": "1706637503", "user": "mseidel42"}