{"additions": 30, "auther_ref": "fixServiceThrowingExceptionAtEndEvent", "auther_sha": "03738d5a6888b18bff70c9c9a9e5a3637f53ed94", "author": "Dr15Jones", "body": "If a Service threw an exception during the ending of a processing transition (e.g. end of Event), the exception would cause an abort rather than being propagated as expected. The problem was the Service signal was generated during the destructor of a guard class instance. In C++11 those destructors are now implicitly noexcept(true) which caused the abort. The destructor were changed to noexcept(false) and a new method allowThrow() was added which is used to avoid throwing an exception while an exception is being propagated out of the function which uses the guard.\n", "branch": "CMSSW_7_0_X", "changed_files": 2, "closed_at": "1384942433", "comments": 5, "commits": 1, "created_at": "1384813223", "deletions": 6, "labels": ["core-approved", "fully-signed", "tests-approved"], "merge_commit_sha": "5a36cd44f99b28ddf0465471ecbded2c1cedb313", "merged_at": "1384942433", "merged_by": "ktf", "milestone": "CMSSW_7_0_0_pre9", "number": 1508, "release-notes": [], "review_comments": 0, "state": "closed", "title": "Fixed bug that cause Service exceptions to cause aborts", "updated_at": "1385217144", "user": "Dr15Jones"}