{"additions": 35, "auther_ref": "py3-sqlalchemy-1.3.10", "auther_sha": "e7322933f3fd4240d094a638d6382564c6c40295", "author": "cms-sw", "body": "This should fix the O2O unit test failing in Py3 IB. This happened as we moved to sqlalchemy 1.3.10 which had some changes breaking python3 ", "branch": "IB/CMSSW_11_0_X/master", "changed_files": 3, "closed_at": "1573015738", "comments": 11, "commits": 2, "created_at": "1572987188", "deletions": 14, "labels": ["comparison-available", "externals-approved", "fully-signed", "orp-pending", "tests-approved"], "merge_commit_sha": "7340fd703c15d5abe025f16046bc6c6c54e2120a", "merged_at": "1573015738", "merged_by": "smuzaffar", "number": 5334, "release-notes": [], "review_comments": 0, "state": "closed", "title": "patch sqlalchemy 1.3.10 for python3", "updated_at": "1573015788", "user": "smuzaffar"}