{"additions": 3, "auther_ref": "fs-reverte", "auther_sha": "d2e8c2c6d899d9f0d025d569d0896ca92a1a6c55", "author": "gudrutis", "body": "Problem:\r\n'xrootdpyfs' depends on 'fs' versions (>=0.4.0,<2.0), it was not listed as dependency.\r\n\r\nResolution:\r\n'fs' reverted to version 0.5.5a1, listed as 'xrootdpyfs' dependency.", "branch": "IB/CMSSW_9_4_X/gcc630", "changed_files": 2, "closed_at": "1506094994", "comments": 8, "commits": 1, "created_at": "1506081251", "deletions": 3, "labels": ["externals-pending", "orp-pending", "pending-signatures", "tests-approved"], "merge_commit_sha": "4aab533d22fc856b825e3ab1cb604441645fbd9e", "merged_at": "1506094994", "merged_by": "smuzaffar", "number": 3445, "release-notes": [], "review_comments": 0, "state": "closed", "title": "Resolution to issue #3341- fix xrootdpyfs", "updated_at": "1506094994", "user": "gudrutis"}