{"additions": 36, "auther_ref": "BackportPython3FixPU", "auther_sha": "0c90879c3080406014eaa30131224c904de67255", "author": "kpedro88", "body": "#### PR description:\r\n\r\n`pileupCalc.py` is broken in 10_2_X. Since this is the analysis release, this important script should be usable. I backported the fix that entered 10_3_X, as well as fixes to other scripts from the package  `RecoLuminosity/LumiDB`.\r\n\r\n#### PR validation:\r\n\r\nModified package compiles and `pileupCalc.py` runs successfully.\r\n\r\n#### if this PR is a backport please specify the original PR:\r\n\r\nPartial backport of #24301", "branch": "CMSSW_10_2_X", "changed_files": 3, "closed_at": "1558956941", "comments": 9, "commits": 1, "created_at": "1558620328", "deletions": 33, "labels": ["comparison-available", "db-pending", "orp-approved", "pending-signatures", "tests-approved"], "merge_commit_sha": "f24285d003bd1aa4c881b75ae580df5c3daf50a1", "merged_at": "1558956941", "merged_by": "cmsbuild", "milestone": "CMSSW_10_2_X", "number": 26911, "release-notes": [], "review_comments": 0, "state": "closed", "title": "backport python3 fixes to pileup scripts", "updated_at": "1558956941", "user": "kpedro88"}