{"additions": 1, "auther_ref": "smuzaffar-patch-1", "auther_sha": "f00cad8376eb16af2e1b26ec7afff5db6c9b2feb", "author": "cms-sw", "body": "Backport of #3931\r\nA crash was found in Phase2 production using 9_3_6: see detail here cms-externals/pythia8#10", "branch": "IB/CMSSW_9_3_X/gcc630", "changed_files": 1, "closed_at": "1524158567", "comments": 13, "commits": 1, "created_at": "1524084201", "deletions": 1, "labels": ["backport-ok", "externals-approved", "fully-signed", "orp-pending", "tests-approved"], "merge_commit_sha": "34bd1e264ae0bcb51d2d2ea1fe9f8e2d30270ff1", "merged_at": "1524158567", "merged_by": "cmsbuild", "number": 3932, "release-notes": [], "review_comments": 0, "state": "closed", "title": "Update pythia8.spec", "updated_at": "1524158567", "user": "smuzaffar"}