{"additions": 1, "auther_ref": "smuzaffar-patch-1", "auther_sha": "f00cad8376eb16af2e1b26ec7afff5db6c9b2feb", "author": "cms-sw", "body": "Backport of #3931\r\nA crash was found in Phase2 production using 9_3_6: see detail here cms-externals/pythia8#10", "branch": "IB/CMSSW_9_3_X/gcc630", "changed_files": 1, "comments": 3, "commits": 1, "created_at": "1524084201", "deletions": 1, "labels": ["backport", "externals-pending", "orp-pending", "pending-signatures", "tests-started"], "number": 3932, "release-notes": [], "review_comments": 0, "state": "open", "title": "Update pythia8.spec", "updated_at": "1524084227", "user": "smuzaffar"}