{"additions": 16, "auther_ref": "fixServiceThrowingExceptionAtEndEventFor6_2_X", "auther_sha": "ce19868860162697d01d564cb000d1dc6ac8998d", "author": "Dr15Jones", "body": "If a Service threw an exception during the ending of a processing transition (e.g. end of Event), the exception would cause an abort rather than being propagated as expected.\nThe problem was the Service signal was generated during the destructor of a 'guard' class instance. In C++11 those destructors are now implicitly noexcept(true) which caused the abort.\nThe destructor were changed to noexcept(false) and a new method 'allowThrow()' was added which is used to avoid throwing an exception while an exception is being propagated out\nof the function which uses the guard.\n\nThis fix was already introduced to CMSSW_7_0_X but given the large changes between the two releases this had to be reimplemented by hand.\n", "branch": "CMSSW_6_2_X", "changed_files": 1, "closed_at": "1385296235", "comments": 3, "commits": 1, "created_at": "1384875407", "deletions": 3, "labels": ["core-approved", "fully-signed", "tests-pending"], "merge_commit_sha": "d42f36510a81bc60037d2ed9dc68d43c650a246c", "merged_at": "1385296235", "merged_by": "davidlt", "milestone": "CMSSW_6_2_4", "number": 1526, "release-notes": [], "review_comments": 0, "state": "closed", "title": "Fixed bug that cause Service exceptions to cause aborts", "updated_at": "1387469923", "user": "Dr15Jones"}