{"additions": 20, "auther_ref": "protectTTreeAccessAfterException_7_6", "auther_sha": "479c3f94e22ae6fde5cd25d77b333aa538d36897", "author": "Dr15Jones", "body": "Since TTree is not exception safe, we must avoid calling TTree methods after we have had an exception thrown through TTree. Normally this happens when one thread throws an exception while another thread is waiting to access the same TTree.\nThis should avoid crashes seen in the Tier 0.\n", "branch": "CMSSW_8_0_X", "changed_files": 2, "closed_at": "1449172850", "comments": 2, "commits": 1, "created_at": "1449172710", "deletions": 2, "labels": ["comparison-pending", "core-pending", "orp-pending", "pending-signatures", "tests-pending"], "milestone": "CMSSW_8_0_X", "number": 12661, "release-notes": [], "review_comments": 0, "state": "closed", "title": "Do not call TTree cache after an exception happens", "updated_at": "1449600389", "user": "Dr15Jones"}