{"additions": 98, "auther_ref": "fixErrorReturnCode132X", "auther_sha": "e1a3683a5ce9a8fc20f10c5d08c25cacd96954de", "author": "wddgit", "body": "#### PR description:\r\n\r\nFix error code returned by cmsRun on a FallbackFileOpenError. There was a bug where it returns FileOpenError even in the fallback case.\r\n\r\nThere is more discussion and more information related to this bug in issue https://github.com/cms-sw/cmssw/issues/42040. FYI @stlammel\r\n\r\n#### PR validation:\r\n\r\nIncludes new unit test. New unit test and exiting tests pass. This should only affect the behavior after an exception occurs. It should not affect the output of successful cmsRun processes.\r\n\r\nBackport of #42249.\r\n", "branch": "CMSSW_13_2_X", "changed_files": 8, "comments": 2, "commits": 1, "created_at": "1690380172", "deletions": 2, "labels": ["core-pending", "pending-signatures", "orp-pending", "tests-started"], "milestone": "CMSSW_13_2_X", "number": 42379, "release-notes": [], "review_comments": 0, "state": "open", "title": "Fix error code on fallback file open error with test, 13_2_X backport", "updated_at": "1690380403", "user": "wddgit"}