{"additions": 11, "auther_ref": "FixUBSANEnum", "auther_sha": "c94271286dfe9d050dc3c876ee2e004fce7a1386", "author": "emilbols", "body": "#### PR description:\r\n\r\nIssue: https://github.com/cms-sw/cmssw/issues/35033\r\n\r\n```\r\n1302.17 step3\r\nDataFormats/BTauReco/interface/TemplatedSecondaryVertexTagInfo.h:38:21: runtime error: load of value 4, which is not a valid value for type 'Status'\r\n```\r\nAn enum object is currently manipulated to be outside its defined range in BTV code, which is considered undefined behavior with the UBSAN IB. This fix changes this enum structure to be integer based instead, which should get rid of the error, while not changing any behavior. \r\n\r\n#### PR validation:\r\n\r\nAs i had some issues reproducing the issues, i used a specific step2.root file [1] in workflow 1302.17 step3\r\n```\r\ncmsDriver.py step3  -s RAW2DIGI,L1Reco,RECO,RECOSIM,EI,PAT --conditions auto:phase1_2017_realistic -n 10 --datatier AODSIM,MINIAODSIM --eventcontent AODSIM,MINIAODSIM --era Run2_2017 --filein file:step2.root  --fileout file:step3.root  --nThreads 4 > step3_ProdTTbar_13UP17+ProdTTbar_13UP17+DIGIUP17PROD1+RECOPRODUP17.log  2>&1\r\n```\r\nWith CMSSW_12_1_UBSAN_X_2021-09-03-2300 I get the reported error every time on event 10. After applying this fix, this error is gone.\r\n\r\n[1]\r\nhttps://cernbox.cern.ch/index.php/s/8vFa8hmOo9P94jf\r\n\r\n", "branch": "master", "changed_files": 3, "closed_at": "1631333609", "comments": 17, "commits": 3, "created_at": "1631104991", "deletions": 12, "labels": ["reconstruction-approved", "fully-signed", "tests-approved", "orp-approved", "code-checks-approved"], "merge_commit_sha": "01a879ae0518ceba36a1ce5f3b199e31a27673f0", "merged_at": "1631333609", "merged_by": "cmsbuild", "milestone": "CMSSW_12_1_X", "number": 35197, "release-notes": [], "review_comments": 2, "state": "closed", "title": "[UBSAN] Fix overloaded enum in TemplatedSecondaryVertexTagInfo", "updated_at": "1631333609", "user": "emilbols"}