{"additions": 111, "auther_ref": "exceptionInEventProcessorCtr_12_4", "auther_sha": "ab7ea0f11f74ec7fcda3a62bcdbd608700080191", "author": "Dr15Jones", "body": "#### PR description:\r\n\r\nIf an exception happens in the constructor, delete the object in the order done explicitly in the destructor while the Services are active.\r\n\r\n#### PR validation:\r\n\r\nFramework unit tests pass\r\n\r\n#### if this PR is a backport please specify the original PR and why you need to backport that PR:\r\n\r\nBackport of #38144 ", "branch": "CMSSW_12_4_X", "changed_files": 1, "comments": 2, "commits": 1, "created_at": "1654019770", "deletions": 99, "labels": ["core-pending", "pending-signatures", "orp-pending", "tests-started"], "milestone": "CMSSW_12_4_X", "number": 38153, "release-notes": [], "review_comments": 0, "state": "open", "title": "Deal with exception in EventProcessor constructor [12_4]", "updated_at": "1654020035", "user": "Dr15Jones"}