{"additions": 111, "auther_ref": "exceptionInEventProcessorCtr_12_4", "auther_sha": "ab7ea0f11f74ec7fcda3a62bcdbd608700080191", "author": "Dr15Jones", "body": "#### PR description:\r\n\r\nIf an exception happens in the constructor, delete the object in the order done explicitly in the destructor while the Services are active.\r\n\r\n#### PR validation:\r\n\r\nFramework unit tests pass\r\n\r\n#### if this PR is a backport please specify the original PR and why you need to backport that PR:\r\n\r\nBackport of #38144 ", "branch": "CMSSW_12_4_X", "changed_files": 1, "closed_at": "1654186439", "comments": 6, "commits": 1, "created_at": "1654019770", "deletions": 99, "labels": ["core-approved", "fully-signed", "tests-approved", "orp-approved"], "merge_commit_sha": "84fa85b819d24cf39dc8dea9fe9460c28d755210", "merged_at": "1654186439", "merged_by": "cmsbuild", "milestone": "CMSSW_12_4_X", "number": 38153, "release-notes": [], "review_comments": 0, "state": "closed", "title": "Deal with exception in EventProcessor constructor [12_4]", "updated_at": "1654186439", "user": "Dr15Jones"}