{"additions": 134, "auther_ref": "fixErrorReturnCode", "auther_sha": "40155e06da8ed372e66c778559f6fe98d8378bc8", "author": "wddgit", "body": "#### PR description:\r\n\r\nFix error code returned by cmsRun on a FallbackFileOpenError. There was a bug where it returns FileOpenError even in the fallback case.\r\n\r\nThere is more discussion and more information related to this bug in issue #42040. FYI @stlammel\r\n\r\nAlso added a unit test so this bug will not recur.\r\n\r\nAlso I noticed a case where a misconfigured storage.json file could cause a seg fault. I added a check for that case and now it throws an exception with an informative error message (remains fatal as before).\r\n\r\n#### PR validation:\r\n\r\nNew unit test passes and existing unit tests pass. This should only affect the behavior after an exception or seg fault occurs. It should not affect the output of successful cmsRun processes.\r\n", "branch": "master", "changed_files": 11, "comments": 7, "commits": 1, "created_at": "1689173822", "deletions": 2, "labels": ["core-pending", "pending-signatures", "orp-pending", "tests-started", "code-checks-approved"], "milestone": "CMSSW_13_2_X", "number": 42249, "release-notes": [], "review_comments": 4, "state": "open", "title": "Fix error code returned by cmsRun on a FallbackFileOpenError", "updated_at": "1689256467", "user": "wddgit"}