{"additions": 45, "auther_ref": "pydata_fix_70X", "auther_sha": "7754c8fe05e2d22898f5802064b425ea44036ab6", "author": "mkirsano", "body": "", "branch": "CMSSW_7_0_X", "changed_files": 1, "closed_at": "1389791227", "comments": 7, "commits": 1, "created_at": "1389610472", "deletions": 0, "labels": ["fully-signed", "generators-approved", "tests-approved"], "merge_commit_sha": "a88e262011ede299c45f42b45cb25077aeb8f409", "merged_at": "1389791227", "merged_by": "ktf", "milestone": "CMSSW_7_0_0_pre12", "number": 2009, "release-notes": [], "review_comments": 0, "state": "closed", "title": "fix pydata loading problem, ported from 6_2_X", "updated_at": "1389791227", "user": "mkirsano"}